### ISSUE TITLE
auth: DNSBackend and Ueberbacked cleanup meta issue

### ISSUE THREAD

**Issue by RobinGeuze** [PowerDNS/pdns#10590]
- Program: Authoritative
 - Issue type: Feature request

### Short description

The ::get methodology currently used within dnsbackend doesn't make much sense for a bunch of backends, so we should get rid of it. There is also a bunch of redundant or partially redundant functions in dnsbackend that can potentially be merged, removed or improved.

### Usecase

This will improve code quality, potentially performance, and reduce complexity.

### Description

Rough list of things that should probably happen:
- [ ] Remove ::get from ::lookup in DNSBackend, initial work in #10534
- [ ] Merge ::list and ::listSubZone in DNSBackend
- [ ] Remove ::get from ::list/::listSubZone in DNSBackend
- [ ] Remove ::get from UeberBackend
- [ ] Improve querycache (make it so inserting something into the cache returns a reference to that item, or the old reference is returned)
- [ ] Allow viewing and removing of supermasters #10582
- [ ] Standardize everything on DNSZoneRecord rather than support both DNSResourceRecord and DNSZoneRecord
- [ ] Optimize backends to the new world without ::get
- [ ] Look at other functions in DNSBackend to determine necessity
- [ ] Update and expand backend writers guide.
