### ISSUE TITLE
auth: gsql schema cleanup

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#11895]
Over the years, the gsql schemas for the various backends have accumulated some accidents. There were also accidents in the first versions of the schemas. This ticket collects them.

* [ ] Y2038-problems #11872
* [ ] various columns in various schemas could be simplified to TEXT (please read all comments in #11836)

**Comment by hlindqvist** [comment]
- [ ] The gmysql schema started out without specifying a charset for character types ([example](https://github.com/PowerDNS/pdns/blob/7166723ee2eb75c36cd689dd80b01d6fdbe8d068/modules/gmysqlbackend/schema.mysql.sql#L1)), inheriting the default from the db environment.  
When this was later improved for new installations, the migration steps did not change the charset for already existing columns, instead only the default charset applied to any newly created columns was changed ([example](https://github.com/PowerDNS/pdns/blob/master/modules/gmysqlbackend/3.4.0_to_4.1.0_schema.mysql.sql#L2)).  
Seemingly if your environment used a different charset than 'latin1' when the tables were originally created, the original character-type columns will still be in that other charset after applying all the migration scripts.  
See also: https://dev.mysql.com/doc/refman/8.0/en/alter-table.html#alter-table-character-set

**Comment by silverwind** [comment]
There is another issue, some columns specify deprecated `utf8` charset:

https://github.com/PowerDNS/pdns/blob/bb10ed912e06ee33b501dc38e9fcfb1ca99a6707/modules/gmysqlbackend/schema.mysql.sql#L52

There was https://github.com/PowerDNS/pdns/pull/8622 that would have fixed. Keep note that future MySQL will likely [re-alias](https://dev.mysql.com/doc/refman/8.2/en/charset-unicode-utf8.html) `utf8` to `utf8mb4` at which point these tables will be created with a proper utf8 charset:

>  The utf8mb3 character set is deprecated and you should expect it to be removed in a future MySQL release. Please use utf8mb4 instead. utf8 is currently an alias for utf8mb3, but it is now deprecated as such, and utf8 is expected subsequently to become a reference to utf8mb4. In MySQL 8.2, utf8mb3 is also displayed in place of utf8 in columns of Information Schema tables, and in the output of SQL SHOW statements.

**Comment by murphy83** [comment]
Just stumbled upon another issue when upgrading my instance to Version 4.7. => the given documentation for migration contains:
```ALTER TABLE domains ADD options VARCHAR(64000) DEFAULT NULL;```
Which causes errors with at least MariaDB 10.6 => you need to use TEXT as datatype for the option field in this case.

Maybe even the idea of using a database-versioning system such as Liquibase might be handy, especially for systems running docker based and therefor highly automated => Deploy a new version of the container should also take care of upgrading the database if this is required by an update.

**Comment by miodvallat** [comment]
- [ ] `master` field in gmysql `domains` table is currently too small for some real-world needs (#13490)
- [ ] Add more indexes for performance (#9258)
- [ ] Sqlite3 STRICT changes (#13958)
- [ ] Update schema to prevent duplicate zone metadata records (#2214)
- [ ] Some people might want to see the record change timestamp column back (#2211)
- [ ] Make more fields "NOT NULL" (#2388)
- [ ] More readable postgresql queries (#11107)
